[font]
size = 18

[font.bold]
family = "DepartureMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "DepartureMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "DepartureMono Nerd Font"
style = "Italic"

[font.normal]
family = "DepartureMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[window]
opacity = 0.9

[window.dimensions]
columns = 130
lines = 50

[window.padding]
x = 0
y = 0
